# Values for 2 base Istio charts
# https://github.com/istio/istio/tree/master/manifests/charts


istiod:
  pilot:
    # Resources for a small pilot install
    resources:
      requests:
        cpu: 500m
        memory: 512M
    proxy:
      # Resources for the sidecar.
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 2000m
          memory: 1024Mi