apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: istio-ingressgateway
spec:
  secretName: argocd-cert
  commonName: argocd.${{ .Values.clusterIngressDomain }}
  dnsNames:
  - argocd.${{ .Values.clusterIngressDomain }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer