apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: argocd-ingress
  namespace: istio-ingressgateway
spec:
  selector:
    app: istio-ingressgateway
  servers:
  - port:
      number: 443
      name: https-443-argo
      protocol: HTTPS
    hosts:
    - argocd.gke.nategramer.com
    tls:
      mode: SIMPLE # enables HTTPS on this port
      credentialName: argocd-cert # fetches certs from Kubernetes secret