apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
spec:
  gateways:
  - argocd-ingress
  hosts:
  - argocd.gke.nategramer.com
  http:
  - name: "argocd"
    route:
    - destination:
        host: argocd-server.argocd.svc.cluster.local