apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-ingressgateway
spec:
  secretName: ingress-cert
  commonName: gke.nategramer.com
  dnsNames:
  - gke.nategramer.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer