apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-ingressgateway
spec:
  secretName: ingress-cert
  commonName: ${{ .Values.clusterIngressDomain }}
  dnsNames:
  - ${{ .Values.clusterIngressDomain }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer