apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingressgateway
  namespace: istio-ingressgateway
spec:
  selector:
    app: istio-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - ${{ .Values.clusterIngressDomain }}
    tls:
      httpsRedirect: false # Configured on virtual service, cert-manager needs to solve via http
  
  - port:
      number: 80
      name: http-wildcard
      protocol: HTTP
    hosts:
    - "*.${{ .Values.clusterIngressDomain }}"
    tls:
      httpsRedirect: false # Configured on virtual service, cert-manager needs to solve via http

  - port:
      number: 443
      name: https-443
      protocol: HTTPS
    hosts:
    - ${{ .Values.clusterIngressDomain }}
    tls:
      mode: SIMPLE # enables HTTPS on this port
      credentialName: ingress-cert # fetches certs from Kubernetes secret