# https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd#installing-the-chart

clusterIngressDomain: ""

argo-cd:
  applicationSet:
    enabled: false

  configs:
    params:
      server.insecure: true # TLS handled by istio
    cm:
      url: https://argocd.gke.nategramer.com

  controller:
    resources: {}

  dex:
    enabled: false

  notifications:
    enabled: false

  repoServer:
    resources: {}

  redis:
    resources: {}
  
  redis-ha:
    enabled: false
    haproxy:
      enabled: false

  server:
    resources: {}