# https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd#installing-the-chart

argo-cd:
  applicationSet:
    enabled: false

  configs:
    params:
      server:
        insecure: true # TLS handled by istio
    cm:
      url: https://argo.nategramer.com

  controller:
    resources: {}

  dex:
    enabled: false

  notifications:
    enabled: false

  repoServer:
    resources: {}

  redis:
    resources: {}

  server:
    resources: {}